CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    email    VARCHAR(320) NOT NULL,
    login    VARCHAR(64)  NOT NULL,
    name     VARCHAR(128) NOT NULL,
    birthday DATE,

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_login UNIQUE (login),

    CONSTRAINT chk_users_email_not_blank CHECK (TRIM(email) <> ''),
    CONSTRAINT chk_users_login_not_blank CHECK (TRIM(login) <> ''),
    CONSTRAINT chk_users_name_not_blank CHECK (TRIM(name) <> '')
);

CREATE TABLE IF NOT EXISTS friendship
(
    requester_id      BIGINT  NOT NULL,
    addressee_id      BIGINT  NOT NULL,

    addressee_deleted boolean NOT NULL DEFAULT FALSE,
    status            boolean NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_friendship PRIMARY KEY (requester_id, addressee_id),

    CONSTRAINT fk_friendship_requester FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_friendship_addressee FOREIGN KEY (addressee_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT chk_friendship_not_self CHECK (requester_id <> addressee_id)

);

CREATE INDEX IF NOT EXISTS idx_friendship_addressee_id ON friendship (addressee_id);

CREATE TABLE IF NOT EXISTS genres
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,

    CONSTRAINT uq_genres_name UNIQUE (name),
    CONSTRAINT chk_genres_name_not_blank CHECK (TRIM(name) <> '')
);

CREATE TABLE IF NOT EXISTS mpa
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,

    CONSTRAINT uq_mpa_name UNIQUE (name),
    CONSTRAINT chk_mpa_name_not_blank CHECK (TRIM(name) <> '')
);

CREATE TABLE IF NOT EXISTS film
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    mpa_id       INT,
    description  CLOB,
    release_date DATE,
    duration     INT,

    CONSTRAINT fk_films_mpa FOREIGN KEY (mpa_id) REFERENCES mpa (id) ON DELETE RESTRICT,

    CONSTRAINT chk_films_title_not_blank CHECK (TRIM(title) <> ''),
    CONSTRAINT chk_films_duration_pos CHECK (duration IS NULL OR duration > 0)

);

CREATE INDEX IF NOT EXISTS idx_films_mpa_id ON film (mpa_id);

CREATE TABLE IF NOT EXISTS user_film_likes
(
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,

    CONSTRAINT pk_user_film_likes PRIMARY KEY (user_id, film_id),

    CONSTRAINT fk_ufl_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_ufl_film FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_film_likes_film_id ON user_film_likes (film_id);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,

    CONSTRAINT pk_film_genres PRIMARY KEY (film_id, genre_id),

    CONSTRAINT fk_film_genres_film FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE,
    CONSTRAINT k_film_genres_genre FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_film_genres_film_id ON film_genres (film_id);

CREATE TABLE IF NOT EXISTS reviews
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,
    content VARCHAR NOT NULL,
    is_positive BOOLEAN NOT NULL,
    useful INT NOT NULL DEFAULT 0,

    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_film FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE,

    CONSTRAINT chk_reviews_content_not_blank CHECK (TRIM(content) <> ''),
    CONSTRAINT chk_reviews_rating_non_negative CHECK (useful >= 0),

    CONSTRAINT uq_reviews_user_film UNIQUE (user_id, film_id)
    );

CREATE INDEX IF NOT EXISTS idx_reviews_film_id ON reviews (film_id);
CREATE INDEX IF NOT EXISTS idx_reviews_useful ON reviews (useful);

CREATE TABLE IF NOT EXISTS review_reactions
(
    review_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reaction_type VARCHAR(10) NOT NULL,

    CONSTRAINT pk_review_reactions PRIMARY KEY (review_id, user_id),

    CONSTRAINT fk_rr_review FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE,
    CONSTRAINT fk_rr_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT chk_rr_type CHECK (reaction_type IN ('LIKE', 'DISLIKE'))
    );

CREATE INDEX IF NOT EXISTS idx_review_reactions_review_id ON review_reactions (review_id);
