package ru.yandex.practicum.filmorate.dal;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import ru.yandex.practicum.filmorate.dal.friends.FriendsStorage;
import ru.yandex.practicum.filmorate.dal.likes.LikesStorage;
import ru.yandex.practicum.filmorate.dal.user.UserDbStorage;
import ru.yandex.practicum.filmorate.model.user.User;

import java.time.LocalDate;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

@JdbcTest
@Import(UserDbStorage.class)
class UserDbStorageTest {

    private final UserDbStorage userStorage;
    private final NamedParameterJdbcTemplate jdbc;

    @MockBean
    private FriendsStorage friendsStorage;

    @MockBean
    private LikesStorage likesStorage;

    UserDbStorageTest(UserDbStorage userStorage, NamedParameterJdbcTemplate jdbc) {
        this.userStorage = userStorage;
        this.jdbc = jdbc;
    }

    @BeforeEach
    void setUp() {
        var jt = jdbc.getJdbcTemplate();

        jt.execute("DROP TABLE IF EXISTS users");

        jt.execute("""
                CREATE TABLE users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email VARCHAR(320) NOT NULL,
                    login VARCHAR(64) NOT NULL,
                    name VARCHAR(128) NOT NULL,
                    birthday DATE
                )
                """);
    }

    @Test
    @DisplayName("save –– сохраняет пользователя и проставляет id")
    void save_setsId_andPersists() {
        User u = user("a@a.ru", "loginA", "Name A", LocalDate.of(2000, 1, 1));

        User saved = userStorage.save(u);

        assertNotNull(saved.getId());
        assertTrue(saved.getId() > 0);

        User fromDb = userStorage.getById(saved.getId()).orElseThrow();
        assertEquals(saved.getId(), fromDb.getId());
        assertEquals("a@a.ru", fromDb.getEmail());
        assertEquals("loginA", fromDb.getLogin());
        assertEquals("Name A", fromDb.getName());
        assertEquals(LocalDate.of(2000, 1, 1), fromDb.getBirthday());
    }

    @Test
    @DisplayName("getById –– возвращает empty если пользователя нет")
    void getById_returnsEmpty_whenMissing() {
        Optional<User> res = userStorage.getById(999_999L);
        assertTrue(res.isEmpty());
    }

    @Test
    @DisplayName("update –– обновляет поля пользователя")
    void update_updatesFields() {
        User saved = userStorage.save(user("a@a.ru", "loginA", "Name A", LocalDate.of(2000, 1, 1)));

        saved.setEmail("new@a.ru");
        saved.setLogin("newLogin");
        saved.setName("New Name");
        saved.setBirthday(LocalDate.of(1999, 12, 31));

        userStorage.update(saved);

        User fromDb = userStorage.getById(saved.getId()).orElseThrow();
        assertEquals("new@a.ru", fromDb.getEmail());
        assertEquals("newLogin", fromDb.getLogin());
        assertEquals("New Name", fromDb.getName());
        assertEquals(LocalDate.of(1999, 12, 31), fromDb.getBirthday());
    }

    @Test
    @DisplayName("getAll –– возвращает пользователей по возрастанию id")
    void getAll_returnsOrderedById() {
        User u1 = userStorage.save(user("a@a.ru", "a", "A", null));
        User u2 = userStorage.save(user("b@b.ru", "b", "B", null));

        List<User> all = userStorage.getAll();

        assertEquals(2, all.size());
        assertEquals(List.of(u1.getId(), u2.getId()), all.stream().map(User::getId).toList());
    }

    @Test
    @DisplayName("existsById –– true если есть, false если нет")
    void existsById_works() {
        User saved = userStorage.save(user("a@a.ru", "a", "A", null));

        assertTrue(userStorage.existsById(saved.getId()));
        assertFalse(userStorage.existsById(999_999L));
    }

    @Test
    @DisplayName("getByIds –– возвращает список пользователей по набору id")
    void getByIds_returnsUsers() {
        User u1 = userStorage.save(user("a@a.ru", "a", "A", null));
        User u2 = userStorage.save(user("b@b.ru", "b", "B", null));
        userStorage.save(user("c@c.ru", "c", "C", null));

        List<User> found = userStorage.getByIds(Set.of(u1.getId(), u2.getId()));

        assertEquals(2, found.size());

        List<Long> ids = found.stream().map(User::getId).sorted().toList();
        List<Long> expected = List.of(u1.getId(), u2.getId()).stream().sorted(Comparator.naturalOrder()).toList();

        assertEquals(expected, ids);
    }

    private static User user(String email, String login, String name, LocalDate birthday) {
        User u = new User();
        u.setEmail(email);
        u.setLogin(login);
        u.setName(name);
        u.setBirthday(birthday);
        return u;
    }
}
